import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import 'animate.css';
import "./custom.scss";
import BootstrapClient from "@/component/bootstrap-client";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* custom Css*/}
        <link href="/css/frontend.css" rel="stylesheet" type="text/css" />
        <link href="/css/responsive.css" rel="stylesheet" type="text/css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <main className="page-wrapper">
          <Header />

          {/* Render the page content */}
          {children}

          <Footer />
        </main>
        
      </body>
      <BootstrapClient />
    </html>
  );
}
