import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import 'animate.css';
import "./custom.scss";
import BootstrapClient from "@/component/bootstrap-client";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import Script from "next/script";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {

  let courselist = [];
  let booklist = [];
  let courses=[];
  try {

    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/header`, {

      method: 'GET',
      cache: 'no-store'
    })

    const res = await response.json();
    if (res.status) {
      booklist = res.booklist;
      courselist = res.courselist;
      courses=res.courses;
    }

  } catch (error) {

    console.log(error);


  }


  return (


    <html lang="en">
      <head>
        {/* custom Css*/}
        <link href="/css/frontend.css" rel="stylesheet" type="text/css" />
        <link href="/css/responsive.css" rel="stylesheet" type="text/css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <main className="page-wrapper">
          <Header courselist={courselist} booklist={booklist} courses={courses}/>

          {/* Render the page content */}
          {children}

          <Footer />
        </main>

        <Script src="https://checkout.razorpay.com/v1/checkout.js" />

      </body>
      <BootstrapClient />
    </html>
  );
}
